const API="http://127.0.0.1:8090/api";
const $=id=>document.getElementById(id);
let state={units:[],inventory:[],requests:[],files:[],dashboard:null};
const labels={dashboard:"Command Dashboard",units:"Military Units",inventory:"Equipment & Inventory",requests:"Supply Missions",scheduling:"Supply Mission Scheduling",memory:"Depot Storage Allocation",paging:"Mission Data Paging",deadlock:"Equipment Resource Safety",files:"Military Record Management",reports:"Logistics Reports"};
async function api(path,options={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let data={};try{data=await r.json()}catch{}if(!r.ok||data.ok===false)throw new Error(data.error||`HTTP ${r.status}`);return data}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2400)}
function priority(v){return v==1?"HIGH":v==2?"MEDIUM":"LOW"}
function statusClass(s){return s==="Pending"?"pending":s==="Cancelled"?"cancelled":"ok"}
function unitName(id){const u=state.units.find(x=>x.id===id);return u?u.name:`Unit ${id}`}
function equipmentName(id){const e=state.inventory.find(x=>x.id===id);return e?e.name:`Equipment ${id}`}
function renderDashboard(){const d=state.dashboard||{};$("dUnits").textContent=d.units??"—";$("dPersonnel").textContent=d.personnel??"—";$("dEquipment").textContent=d.equipment??"—";$("dPending").textContent=d.pending??"—";$("dAvailable").textContent=d.available??"—";$("dIssued").textContent=d.issued??"—";$("dMemory").textContent=d.pendingMemory??"—";$("dBurst").textContent=d.averageBurst??"—";
$("recent").innerHTML=state.requests.slice(-6).reverse().map(r=>`<tr><td>#${r.id}</td><td>${unitName(r.unit)}</td><td>${equipmentName(r.equipment)}</td><td>${r.quantity}</td><td><span class="${r.priority==1?'ok':r.priority==2?'pending':'cancelled'}">${priority(r.priority)}</span></td><td><span class="${statusClass(r.status)}">${r.status.toUpperCase()}</span></td></tr>`).join("")||`<tr><td colspan="6">No supply missions recorded.</td></tr>`}
function renderUnits(){$("unitsTable").innerHTML=state.units.map(u=>`<tr><td>${u.id}</td><td><b>${u.name}</b></td><td>${u.location}</td><td>${u.personnel}</td><td><span class="ok">REGISTERED</span></td></tr>`).join("")||`<tr><td colspan="5">No units recorded.</td></tr>`}
function renderInventory(){const total=state.inventory.reduce((a,x)=>a+x.quantity,0),avail=state.inventory.reduce((a,x)=>a+x.available,0);$("iTotal").textContent=total;$("iAvailable").textContent=avail;$("iIssued").textContent=total-avail;$("inventoryTable").innerHTML=state.inventory.map(e=>`<tr><td>${e.id}</td><td><b>${e.name}</b></td><td>${e.category}</td><td>${e.quantity}</td><td>${e.available}</td><td><span class="${e.available>0?'ok':'cancelled'}">${e.available>0?'AVAILABLE':'OUT OF STOCK'}</span></td></tr>`).join("")||`<tr><td colspan="6">No equipment recorded.</td></tr>`}
function renderRequests(){const p=state.requests.filter(r=>r.status==="Pending").length,c=state.requests.filter(r=>r.status==="Completed").length;$("rTotal").textContent=state.requests.length;$("rPending").textContent=p;$("rCompleted").textContent=c;$("requestsTable").innerHTML=state.requests.map(r=>`<tr><td>#${r.id}</td><td>${unitName(r.unit)}</td><td>${equipmentName(r.equipment)}</td><td>${r.quantity}</td><td>${priority(r.priority)}</td><td>${r.burst}</td><td>${r.memory} MB</td><td><span class="${statusClass(r.status)}">${r.status.toUpperCase()}</span></td><td class="action">${r.status==="Pending"?`<button onclick="processRequest(${r.id})">Process</button><button class="cancel" onclick="cancelRequest(${r.id})">Cancel</button>`:"—"}</td></tr>`).join("")||`<tr><td colspan="9">No supply missions recorded.</td></tr>`}
function renderFiles(){$("filesTable").innerHTML=state.files.map(f=>`<tr><td>${f.id}</td><td><b>${f.name}</b></td><td>${f.size}</td><td>${f.allocation||"CONTIGUOUS"}</td><td><span class="ok">PERSISTED</span></td></tr>`).join("")||`<tr><td colspan="5">No military records recorded.</td></tr>`}
async function loadAll(){const [d,u,i,r,f,rep]=await Promise.all([api("/dashboard"),api("/units"),api("/inventory"),api("/requests"),api("/files"),api("/reports")]);state={dashboard:d,units:u.units||[],inventory:i.inventory||[],requests:r.requests||[],files:f.files||[]};renderDashboard();renderUnits();renderInventory();renderRequests();renderFiles();$("report").textContent=rep.report||""}
function openPage(page){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===page));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("crumb").textContent=labels[page]||page;$("layout").classList.remove("menu-open");window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>openPage(n.dataset.page));document.querySelectorAll("[data-open]").forEach(x=>x.onclick=()=>openPage(x.dataset.open));$("menuBtn").onclick=()=>$("layout").classList.toggle("menu-open");$("refresh").onclick=async()=>{try{await loadAll();toast("Live data refreshed")}catch(e){toast(e.message)}};
document.querySelectorAll("[data-modal]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".modal").forEach(m=>m.classList.remove("open"));$(b.dataset.modal).classList.add("open");$("modalBg").classList.add("open")});document.querySelectorAll(".close").forEach(b=>b.onclick=closeModal);$("modalBg").onclick=e=>{if(e.target===$("modalBg"))closeModal()};function closeModal(){$("modalBg").classList.remove("open");document.querySelectorAll(".modal").forEach(m=>m.classList.remove("open"))}
window.processRequest=async id=>{try{await api(`/requests/${id}/process`,{method:"POST"});await loadAll();toast(`Mission #${id} processed; inventory updated`)}catch(e){toast(e.message)}};window.cancelRequest=async id=>{try{await api(`/requests/${id}/cancel`,{method:"POST"});await loadAll();toast(`Mission #${id} cancelled`)}catch(e){toast(e.message)}};
$("unitForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/units",{method:"POST",body:JSON.stringify({name:f.get("name"),location:f.get("location"),personnel:+f.get("personnel")})});e.target.reset();closeModal();await loadAll();toast("Military unit registered")}catch(x){toast(x.message)}};
$("equipmentForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/inventory",{method:"POST",body:JSON.stringify({name:f.get("name"),category:f.get("category"),quantity:+f.get("quantity")})});e.target.reset();closeModal();await loadAll();toast("Equipment added to inventory")}catch(x){toast(x.message)}};
$("requestForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/requests",{method:"POST",body:JSON.stringify({unit:+f.get("unit"),equipment:+f.get("equipment"),quantity:+f.get("quantity"),priority:+f.get("priority"),burst:+f.get("burst"),memory:+f.get("memory")})});e.target.reset();closeModal();await loadAll();toast("Supply mission created")}catch(x){toast(x.message)}};
$("fileForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api("/files",{method:"POST",body:JSON.stringify({name:f.get("name"),size:+f.get("size")})});e.target.reset();closeModal();await loadAll();toast("Military record created")}catch(x){toast(x.message)}};
$("runSched").onclick=async()=>{try{const a=encodeURIComponent($("schedAlgo").value),q=+$(`quantum`).value,r=await api(`/scheduling?algorithm=${a}&quantum=${q}`);let rows=r.segments.map(x=>`Mission #${x.id}: ${x.start} → ${x.end}`).join("\n");$("schedResult").textContent=`ALGORITHM : ${r.algorithm}\n\n${rows||"No pending missions."}\n\nTOTAL EXECUTION TIME : ${r.total}`;}catch(e){$("schedResult").textContent="Error: "+e.message}};
$("runMemory").onclick=async()=>{try{const method=encodeURIComponent($("memoryAlgo").value),blocks=encodeURIComponent($("blocks").value),processes=encodeURIComponent($("processes").value),r=await api(`/memory?method=${method}&blocks=${blocks}&processes=${processes}`);$("memoryResult").textContent=`METHOD : ${r.method}\n\n${r.results.map(x=>`Supply load ${x.process} → ${x.block?`Depot Block ${x.block}`:"NOT ALLOCATED"}`).join("\n")}`;}catch(e){$("memoryResult").textContent="Error: "+e.message}};
$("runPaging").onclick=async()=>{try{const a=encodeURIComponent($("pagingAlgo").value),refs=encodeURIComponent($("refs").value),frames=+$(`frames`).value,r=await api(`/paging?algorithm=${a}&frames=${frames}&refs=${refs}`);$("pagingResult").textContent=`ALGORITHM : ${r.algorithm}\nFRAMES    : ${r.frames}\n\nPAGE FAULTS : ${r.faults}\nPAGE HITS   : ${r.hits}\nTOTAL      : ${r.total}\nHIT RATE   : ${(r.hits/r.total*100||0).toFixed(1)}%`;}catch(e){$("pagingResult").textContent="Error: "+e.message}};
$("export").onclick=async()=>{try{const r=await api("/reports"),b=new Blob([r.report],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="MIL-LOG-logistics-report.txt";a.click();URL.revokeObjectURL(a.href);toast("Logistics report exported")}catch(e){toast(e.message)}};
(async()=>{try{await api("/health");$("apiStatus").textContent="● C API ONLINE";await loadAll()}catch(e){$("apiStatus").textContent="● C API OFFLINE";toast("C API offline — start mil-log-api");$("report").textContent="C API is offline.\n\nStart from backend:\n./mil-log-api"}})();
